version: '3'

services:
  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  dynamodb:
    image: cnadiminti/dynamodb-local:latest
    container_name: dynamodb
    volumes:
      - data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
volumes:
  data:

